# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  主页: /
  交流群: https://jq.qq.com/?_wv=1027&k=5Fsmox0
  关于我们: About
  GitHub: https://github.com/LinkMUN
rss: /atom.xml

since: 2016

# Set default keywords (Use a comma to separate)
keywords: "模拟联合国"

# Put your favicon.ico or avatar.jpg into `hexo-site/themes/hiker/source/` directory.
avatar: 
  enable: true
  border: false
  width: 124
  height: 124
  top: 0
  url: css/images/mylogo.png


# Homepage
# eg. home_background_image: [css/images/home-bg.jpg, http://t.cn/RMbvEza]
# eg. mode: image | polyline | trianglify
home_background_image:
  enable: true
  mode: image
  rolling: true
  url: [https://oss.linkmun.com/assets/cover.jpg, https://oss.linkmun.com/assets/home-bg.jpg, https://oss.linkmun.com/assets/welcome-cover.jpg]

home_logo_image:
  enable: false
  border: true
  url: css/images/homelogo.jpg


# AboutPage background
about_big_image: [https://oss.linkmun.com/assets/cover.jpg, https://oss.linkmun.com/assets/home-bg.jpg, https://oss.linkmun.com/assets/welcome-cover.jpg]


# Archive pagination
archive_pagination: true


# Post Article's Content
post_catalog:
  enable: true
# 开启主页摘要
post_excerpt: true


# Content
fancybox: true


# Sidebar
sidebar: left
widgets:
- social
- category
- tag
- tagcloud
- archive
- recent_posts


# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/LinkMUN
  Weibo:
  Twitter: 
  Facebook: 
  Google-plus: 
  Instagram: 
  Pinterest: 
  Flickr: 
  email: admin@linkmun.com


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname: 
disqus_shortname: 
livere_shortname: 
uyan_uid: 
wumii: 


# Code Highlight theme
# Available value:
#    default | gray | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# Article theme color
# Available value:
#    random | orange | blue | red | green | black
theme_color: blue


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: F8EdL0Ad1S67Gwl9ukY8bfv3KP6qb7e1JFYkJTA1r34
baidu_site_verification: eHjQ7w9VBI
qihu_site_verification: 27da57550d6ec628753ed9bcf5766e2b

# Miscellaneous
google_analytics: UA-130228380-1
gauges_analytics: 5c02bb312556a129a41de31c
baidu_analytics: 7d8348f6b063e3d59b87c17d98570729
tencent_analytics: 66122256
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1275534426

# busuanzi count
# http://busuanzi.ibruce.info/
show_busuanzi_view_counts: true


# donation button
donate:
    enable: false
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/WeChanQR.png
    alipayImage: https://raw.githubusercontent.com/iTimeTraveler/iTimeTraveler.github.io/site/source/about/donate/images/AliPayQR.jpg
    
# post copyright
copyright:
    enable: false
